DROP TABLE `CHANGEME`.`Donor`;
DROP TABLE `CHANGEME`.`Event`;
DROP TABLE `CHANGEME`.`Donation`;
DROP TABLE `CHANGEME`.`Volunteer`;
DROP TABLE `CHANGEME`.`Beneficiary`;
DROP TABLE `CHANGEME`.`Volunteer_At`;
DROP TABLE `CHANGEME`.`Expenses`;