-- MySQL Script generated by MySQL Workbench
-- Wed Apr 23 17:33:26 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema jakinw1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema jakinw1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jakinw1` DEFAULT CHARACTER SET utf8 ;
USE `jakinw1` ;

-- -----------------------------------------------------
-- Table `jakinw1`.`Donor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jakinw1`.`Donor` (
  `Name` VARCHAR(45) NOT NULL,
  `Phone` INT NOT NULL,
  `Type` VARCHAR(45) NULL,
  PRIMARY KEY (`Name`, `Phone`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jakinw1`.`Donation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jakinw1`.`Donation` (
  `Name` VARCHAR(45) NOT NULL,
  `Date` DATE NOT NULL,
  `Amount` DOUBLE NOT NULL,
  `IsFirst` CHAR(1) NOT NULL,
  `IsRecurring` CHAR(1) NULL,
  PRIMARY KEY (`Name`, `Date`, `Amount`),
  CONSTRAINT `Name`
    FOREIGN KEY (`Name`)
    REFERENCES `jakinw1`.`Donor` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jakinw1`.`Volunteer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jakinw1`.`Volunteer` (
  `Name` VARCHAR(45) NOT NULL,
  `Phone` INT NOT NULL,
  `Hours` INT NULL,
  PRIMARY KEY (`Name`, `Phone`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jakinw1`.`Event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jakinw1`.`Event` (
  `Name` VARCHAR(45) NOT NULL,
  `EventDate` DATE NOT NULL,
  `Location` VARCHAR(45) NULL,
  `Beneficiary` VARCHAR(45) NULL,
  PRIMARY KEY (`Name`, `EventDate`),
  UNIQUE INDEX `EventDate_UNIQUE` (`EventDate` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jakinw1`.`Volunteer_At`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jakinw1`.`Volunteer_At` (
  `Name` VARCHAR(45) NOT NULL,
  `Event` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Name`, `Event`),
  INDEX `Event_idx` (`Event` ASC) VISIBLE,
  CONSTRAINT `EventName`
    FOREIGN KEY (`Event`)
    REFERENCES `jakinw1`.`Event` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `VolName`
    FOREIGN KEY (`Name`)
    REFERENCES `jakinw1`.`Volunteer` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jakinw1`.`Beneficiary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jakinw1`.`Beneficiary` (
  `ID` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Phone` INT NULL,
  `SupportType` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jakinw1`.`Expenses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jakinw1`.`Expenses` (
  `BeneficaryID` INT NOT NULL,
  `Amount` INT NOT NULL,
  `ExpDate` DATE NOT NULL,
  `Category` VARCHAR(45) NULL,
  `Description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`BeneficaryID`, `Amount`, `ExpDate`),
  INDEX `Date_idx` (`ExpDate` ASC) VISIBLE,
  CONSTRAINT `BeneID`
    FOREIGN KEY (`BeneficaryID`)
    REFERENCES `jakinw1`.`Beneficiary` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `EvDate`
    FOREIGN KEY (`ExpDate`)
    REFERENCES `jakinw1`.`Event` (`EventDate`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
